
pool:
  vmImage: 'birchb1024/genyris-build'

steps:
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'only-clean only-init make-jar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
