
pool:
  vmImage: 'Ubuntu 18.04'

container:
  image: 'docker.io/birchb1024/genyris-build:latest'
  options: --user 0:0

steps:
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'binary'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'

