
pool:
  vmImage: 'Ubuntu 18.04'

container: 'docker.io/birchb1024/genyris-build'

steps:
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'binary'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'

