
pool:
  vmImage: 'Ubuntu 18.04'

container:
  image: 'docker.io/birchb1024/genyris-build:latest'
  options: --user 0:0 -e 
  env: { INSTALL4J_LICENSE: $(INSTALL4J_LICENSE) }

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd /genyris
      ant
    noProfile: false
    noRc: false

