
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'make-jar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
