<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>g</string>
	</array>
	<key>name</key>
	<string>Genyris</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b[\d\.]+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(is-instance|map-left|sleep|thread|httpd|include|java:import|u:format|set|display|triple|graph|left|right|intern|function|cons|cadr|cadar|caar|class|def|define|defmacro|df|defmethod|dict|lambda|length|last|list|var|print|setq|tag|the|in|eq?|is?|bound?|.valid?|is-instance?|.format|.match|template|assert|assertEqual|assertNil|equal|null|valid|rest)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(catch|and|or|apply|quote|not|use|tailcall|cond|in|if|import|else|then|do|eval|while|for|assert|assertEqual|raise|\&amp;rest)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>true|nil|stdout</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.self|this</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^@prefix\s[A-Za-z\:\&lt;]+\s</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CSVReader|Thing|Object|Sound|String|Bignum|Symbol|File|Triple|Pipe|Process|Graph|HttpRequest)\b</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\&gt;|-|\+|/|\^|\!|\*|\&lt;|=|car|cdr|\(|\)|\^|\~)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Za-z0-9\_\.\-\:]+)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'[^\']*\'</string>
			<key>name</key>
			<string>string.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(html|head|body|div|span|a|href|pre|verbatim|table|tr|td)\b</string>
			<key>name</key>
			<string>support</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.genyris</string>
	<key>uuid</key>
	<string>002d094e-95fa-4b3a-b4b7-d14343bbbebe</string>
</dict>
</plist>
