package org.genyris.core;

public interface Internable {

	public Symbol internSymbol(Symbol newSym);
	public Symbol internString(String newname);
	public SimpleSymbol BIGNUM();
    public SimpleSymbol BISCUIT();
	public SimpleSymbol CLASSES();
	public SimpleSymbol CLASSNAME();
	public SimpleSymbol CURLY();
	public SimpleSymbol DICT();
	public SimpleSymbol DICTIONARY();
	public SimpleSymbol DOLLAR();
	public SimpleSymbol DOLLAR_AT();
	public SimpleSymbol DYNAMIC_SYMBOL();
	public SimpleSymbol DYNAMICSYMBOLREF();
	public SimpleSymbol EAGERPROC();
	public SimpleSymbol EOF();
	public SimpleSymbol FALSE();
    public SimpleSymbol FILENAME();
    public SimpleSymbol GLOBALGRAPH();
	public SimpleSymbol GRAPH();
	public SimpleSymbol INDENTPARSER();
	public SimpleSymbol JAVACLASS();
	public SimpleSymbol JAVACTOR();
	public SimpleSymbol JAVAMETHOD();
	public SimpleSymbol JAVASTATICMETHOD();
	public SimpleSymbol JAVAWRAPPER();
	public SimpleSymbol LAMBDA();
	public SimpleSymbol LAMBDAM();
	public SimpleSymbol LAMBDAQ();
	public SimpleSymbol LAZYPROC();
	public SimpleSymbol LEFT();
    public SimpleSymbol LINENUMBER();
	public SimpleSymbol NAME();
	public SimpleSymbol NIL();
	public SimpleSymbol OBJECT();
	public SimpleSymbol PAIR();
	public SimpleSymbol PAIREQUAL();
    public SimpleSymbol PAIRSOURCE();
	public SimpleSymbol PARENPARSER();
	public SimpleSymbol PIPE();
	public SimpleSymbol PREDICATE();
	public SimpleSymbol PREFIX();
	public SimpleSymbol PROCEDUREMISSING();
	public SimpleSymbol QUOTE();
	public SimpleSymbol READER();
	public SimpleSymbol REST();
	public SimpleSymbol RIGHT();
	public SimpleSymbol SELF();
	public SimpleSymbol SIMPLESYMBOL();
	public SimpleSymbol SOURCE();
	public SimpleSymbol SQUARE();
	public SimpleSymbol STANDARDCLASS();
	public SimpleSymbol STRING();
	public SimpleSymbol SUBCLASSES();
	public SimpleSymbol SUBCLASSOF();
	public SimpleSymbol SUBJECT();
	public SimpleSymbol SUPERCLASSES();
    public SimpleSymbol TAILCALL();
	public SimpleSymbol TEMPLATE();
	public SimpleSymbol THING();
	public SimpleSymbol TRIPLE();
	public SimpleSymbol TRUE();
    public SimpleSymbol TYPE();
	public SimpleSymbol URISYMBOL();
	public SimpleSymbol VALIDATE();
	public SimpleSymbol VARS();
	public SimpleSymbol WRITER();
	public SimpleSymbol XMLPARSER();


}
