package org.genyris.core;

import org.genyris.exception.GenyrisException;

public interface Internable {

	Symbol internSymbol(Symbol newSym);
	Symbol internString(String newname);
    Symbol internAny(Exp x) throws GenyrisException;
	SimpleSymbol BIGNUM();
    SimpleSymbol BISCUIT();
	SimpleSymbol CLASSES();
	SimpleSymbol CLASSNAME();
	SimpleSymbol CURLY();
	SimpleSymbol DICT();
	SimpleSymbol DICTIONARY();
	SimpleSymbol DOLLAR();
	SimpleSymbol DOLLAR_AT();
	SimpleSymbol DYNAMIC_SYMBOL();
	SimpleSymbol DYNAMICSYMBOLREF();
	SimpleSymbol EAGERPROC();
	SimpleSymbol EOF();
	SimpleSymbol FALSE();
    SimpleSymbol FILENAME();
    SimpleSymbol GLOBALGRAPH();
	SimpleSymbol GRAPH();
	SimpleSymbol INDENTPARSER();
	SimpleSymbol JAVACLASS();
	SimpleSymbol JAVACTOR();
	SimpleSymbol JAVAMETHOD();
	SimpleSymbol JAVASTATICMETHOD();
	SimpleSymbol JAVAWRAPPER();
	SimpleSymbol LAMBDA();
	SimpleSymbol LAMBDAM();
	SimpleSymbol LAMBDAQ();
	SimpleSymbol LAZYPROC();
	SimpleSymbol LEFT();
    SimpleSymbol LENGTH();
    SimpleSymbol LINENUMBER();
	SimpleSymbol NAME();
	SimpleSymbol NIL();
	SimpleSymbol OBJECT();
	SimpleSymbol PAIR();
	SimpleSymbol PAIREQUAL();
    SimpleSymbol PAIRSOURCE();
	SimpleSymbol PARENPARSER();
	SimpleSymbol PIPE();
    SimpleSymbol PLING();
	SimpleSymbol PREDICATE();
	SimpleSymbol PREFIX();
	SimpleSymbol PROCEDUREMISSING();
	SimpleSymbol QUOTE();
	SimpleSymbol READER();
	SimpleSymbol REST();
	SimpleSymbol RIGHT();
	SimpleSymbol SELF();
    SimpleSymbol SEMI();
	SimpleSymbol SIMPLESYMBOL();
	SimpleSymbol SOURCE();
	SimpleSymbol SQUARE();
	SimpleSymbol STANDARDCLASS();
	SimpleSymbol STRING();
	SimpleSymbol SUBCLASSES();
	SimpleSymbol SUBCLASSOF();
	SimpleSymbol SUBJECT();
    SimpleSymbol SUBJECTS();
	SimpleSymbol SUPERCLASSES();
    SimpleSymbol TAILCALL();
	SimpleSymbol TEMPLATE();
	SimpleSymbol THING();
	SimpleSymbol TRIPLE();
	SimpleSymbol TRUE();
    SimpleSymbol TYPE();
	SimpleSymbol URISYMBOL();
	SimpleSymbol VALIDATE();
	SimpleSymbol VARS();
	SimpleSymbol WRITER();
	SimpleSymbol XMLPARSER();
}
