#

GenyrisEssay.pdf : GenyrisEssay.toc GenyrisEssay.aux
	pdflatex GenyrisEssay.tex
	
GenyrisEssay.toc GenyrisEssay.aux : GenyrisEssay.tex
	pdflatex GenyrisEssay.tex

clean : 
	rm GenyrisEssay.toc GenyrisEssay.aux GenyrisEssay.toc GenyrisEssay.pdf GenyrisEssay.out GenyrisEssay.log